/**
 * Architecture Decision Record (Nygard format) generated from the graph and
 * the linter: what the system is, why it's shaped that way, and what risks
 * are still open. Deterministic, so the same diagram yields the same ADR.
 */
import { CATEGORY_META, categoryOf, spec, type Category } from "../catalog";
import type { Graph } from "../graph";
import { lintGraph } from "../lint";
import { PRODUCT } from "@/config/product";

const RATIONALE: Partial<Record<string, string>> = {
  postgres: "PostgreSQL for transactional data: strong consistency, mature tooling, and room to grow with read replicas.",
  mysql: "MySQL for transactional data with broad hosting support.",
  mongodb: "MongoDB for flexible, document-shaped records.",
  dynamodb: "DynamoDB for predictable single-digit-millisecond key lookups at any scale.",
  cassandra: "Cassandra for write-heavy, horizontally partitioned data.",
  elasticsearch: "A search index for full-text and faceted queries the primary store can't serve efficiently.",
  object_storage: "Object storage for blobs and media, keeping large payloads out of the database.",
  data_warehouse: "A warehouse for analytics so reporting never competes with production traffic.",
  vector_db: "A vector store for semantic retrieval.",
  kafka: "Kafka as a durable, replayable event log, so new consumers can be added without touching producers.",
  rabbitmq: "RabbitMQ for routed work queues with acknowledgements.",
  sqs: "A managed queue to decouple slow work from the request path, with a dead-letter queue for poison messages.",
  pubsub: "A pub/sub topic to fan events out to independent subscribers.",
  redis: "Redis as a look-aside cache to absorb repeated reads and protect the database.",
  memcached: "Memcached as a simple, volatile read cache.",
  api_gateway: "An API gateway as the single front door for routing, authentication, and rate limiting.",
  load_balancer: "A load balancer to spread traffic across instances and remove unhealthy ones.",
  cdn: "A CDN to serve static and cacheable content from the edge.",
  waf: "A WAF to filter malicious traffic before it reaches application code.",
  identity_provider: "A managed identity provider instead of hand-rolled authentication.",
  secrets_vault: "A secrets vault so credentials never live in code or environment files.",
  tracing: "Distributed tracing to follow a request across services.",
  metrics: "Metrics for capacity planning and alerting.",
  logging: "Centralized logs for debugging and audit.",
  function: "Serverless functions for spiky, event-driven work that should scale to zero.",
  worker: "Background workers so slow work happens off the request path.",
};

const ALTERNATIVES: Partial<Record<string, string>> = {
  kafka: "SQS or RabbitMQ: simpler to operate, but no replay and weaker ordering guarantees.",
  sqs: "Kafka: replayable and higher throughput, but heavier to operate for plain work queues.",
  rabbitmq: "SQS: fully managed, but fewer routing options.",
  postgres: "DynamoDB: effortless scale, but joins and ad-hoc queries become application code.",
  mongodb: "PostgreSQL with JSONB: one database to run, with relational guarantees.",
  redis: "No cache: simpler, but every read lands on the primary database.",
  api_gateway: "Clients calling services directly: fewer hops, but auth and rate limiting get duplicated in every service.",
};

export function toADR(graph: Graph, title = "System architecture", date = new Date()): string {
  const byCat = new Map<Category, string[]>();
  for (const n of graph.nodes) {
    const c = categoryOf(n.kind);
    byCat.set(c, [...(byCat.get(c) ?? []), `${n.name} (${spec(n.kind).label}${n.replicas > 1 ? `, ×${n.replicas}` : ""})`]);
  }
  const kinds = [...new Set(graph.nodes.map((n) => n.kind))];
  const findings = lintGraph(graph);
  const byId = new Map(graph.nodes.map((n) => [n.id, n]));
  const asyncEdges = graph.edges.filter((e) => e.kind === "async").length;
  const syncEdges = graph.edges.filter((e) => e.kind === "sync").length;
  const plaintext = graph.edges.filter((e) => !e.encrypted).length;

  const lines: string[] = [];
  lines.push(`# ADR: ${title}`, "");
  lines.push(`- **Status:** Proposed`, `- **Date:** ${date.toISOString().slice(0, 10)}`, `- **Generated by:** ${PRODUCT.name} from the live architecture graph`, "");

  lines.push("## Context", "");
  lines.push(
    `The system has ${graph.nodes.length} components and ${graph.edges.length} connections: ${syncEdges} synchronous, ${asyncEdges} asynchronous, and ${graph.edges.length - syncEdges - asyncEdges} replication or cache links.`,
    "",
  );
  for (const [cat, names] of byCat) lines.push(`- **${CATEGORY_META[cat].plural}:** ${names.join(", ")}`);
  lines.push("");

  lines.push("## Decision", "");
  const rationale = kinds.map((k) => RATIONALE[k]).filter(Boolean);
  if (rationale.length) for (const r of rationale) lines.push(`- ${r}`);
  else lines.push("- Start with the components shown and evolve as load and requirements become clear.");
  lines.push("");
  lines.push("### Interactions", "");
  for (const e of graph.edges) {
    const s = byId.get(e.source)?.name;
    const t = byId.get(e.target)?.name;
    if (!s || !t) continue;
    const how = e.kind === "async" ? "publishes to / consumes from" : e.kind === "replication" ? "replicates to" : e.kind === "cache" ? "reads through cache" : "calls";
    lines.push(`- \`${s}\` ${how} \`${t}\` over ${e.protocol}${e.encrypted ? " (TLS)" : " (**plaintext**)"}`);
  }
  lines.push("");

  lines.push("## Consequences", "");
  lines.push("### Positive", "");
  if (asyncEdges) lines.push("- Asynchronous links isolate failures: a slow consumer builds a backlog instead of failing its callers.");
  if (graph.edges.some((e) => e.kind === "cache")) lines.push("- Caching takes most repeat reads off the primary store.");
  if (graph.edges.some((e) => e.kind === "replication")) lines.push("- Replicas provide failover and extra read capacity.");
  if (plaintext === 0 && graph.edges.length) lines.push("- Every connection is encrypted in transit.");
  if (graph.nodes.some((n) => n.kind === "api_gateway")) lines.push("- One gateway centralizes auth, routing, and rate limits.");
  lines.push("", "### Risks and open issues", "");
  if (findings.length) {
    for (const f of findings) lines.push(`- **${f.severity.toUpperCase()}**: ${f.title}. ${f.message}${f.fix ? ` *Suggested fix: ${f.fix.label.toLowerCase()}.*` : ""}`);
  } else {
    lines.push("- The linter reports no open issues.");
  }
  lines.push("");

  const alts = kinds.map((k) => ALTERNATIVES[k] && `- Instead of ${spec(k).label}: ${ALTERNATIVES[k]}`).filter(Boolean);
  if (alts.length) {
    lines.push("## Alternatives considered", "", ...(alts as string[]), "");
  }
  return lines.join("\n");
}
